### PR TITLE
optimize docker setup / reduce local image from 980mb to 530mb

### PR DESCRIPTION
**Pull request by rannysweis**

### CODE REVIEW

**Review by phillipuniverse — COMMENTED** [review]
This makes no sense to me.

I’m really curious if you use [dive](https://github.com/wagoodman/dive) where all the used space is coming from??

**Comment by phillipuniverse** [comment]
The only thing I can think of is if there is a lot of metadata around from building wheels manually if there aren’t prebuilt ones for alpine (which can definitely happen, but seems like you’re preventing that already). Other than that it seems nuts that pulling in Debian would be less overall size than alpine

**Comment by rannysweis** [comment]
> This makes no sense to me.
> 
> I’m really curious if you use [dive](https://github.com/wagoodman/dive) where all the used space is coming from??

This is why I should explain my PRs:

switching to `slim-bullseye` didn't change the size I just read its more stable and is more frequently updated
there are main source of space usage 

1. the libs being installed. I just decided to install packages as they are needed
2. copying folders from the `python-base` image


I used docker desktop to see where most of the data is coming from 

image

**Comment by phillipuniverse** [comment]
> switching to slim-bullseye didn't change the size I just read its more stable and is more frequently updated


But... why is this the PR title? "reduce local image by 500 mb". Oh. I see now 🤦 

> copying folders from the python-base image

I am _very curious_ how you expect anything about your Python code to work if you don't actually have any dependencies from the virtualenv in the final Docker image 🤣 

image

**Comment by rannysweis** [comment]
> > switching to slim-bullseye didn't change the size I just read its more stable and is more frequently updated
> 
> But... why is this the PR title? "reduce local image by 500 mb". Oh. I see now 🤦
> 
> > copying folders from the python-base image
> 
> I am _very curious_ how you expect anything about your Python code to work if you don't actually have any dependencies from the virtualenv in the final Docker image 🤣
> 
> image

since python base is already the base image the other stages already have access to those directories I just had to change the user in the base. so running COPY was redundant

**Review by phillipuniverse — APPROVED** [review]
Oh shit you’re right, it is now me who is the dumdum!!! Allow me to put my jump to conclusions mat back!!

This is maybe the advantage of an extra layer in-between - installing things like gcc or git python-dev or whatever is only relevant to install these Poetry dependencies (and potentially build wheels), then the COPY can happen with the virtualenvironment already created and you can throw away the layer that you needed to build. If you did that you would reduce final image size even more!!

But that’s more complex and savings maybe not worth it anyway.

Good change, as usual when I’m most confident about something and start being an asshole that’s usually when I’m the most wrong!!

**Comment by phillipuniverse** [comment]
Oh and great tip about the Docker UI for getting layer sizes, I haven’t used that before 👍

**Comment by rannysweis** [comment]
> Oh shit you’re right, it is now me who is the dumdum!!! Allow me to put my jump to conclusions mat back!!
> 
> This is maybe the advantage of an extra layer in-between - installing things like gcc or git python-dev or whatever is only relevant to install these Poetry dependencies (and potentially build wheels), then the COPY can happen with the virtualenvironment already created and you can throw away the layer that you needed to build. If you did that you would reduce final image size even more!!
> 
> But that’s more complex and savings maybe not worth it anyway.
> 
> Good change, as usual when I’m most confident about something and start being an asshole that’s usually when I’m the most wrong!!

As I always say to max "I'm always right"

**Comment by rannysweis** [comment]
> 

yes! it was essential to find out what was happening in each layer

**Pull request merged**
